### ISSUE TITLE
VSCode Extension not recognizing buf dependencies in imports

### ISSUE THREAD

**Issue by MartinLoeper** [mercari/grpc-federation#209]
**Describe the bug**
The linter does not recognize dependencies defined in `buf.yaml` (deps key) when imported in our .proto files:

```
[Error - 10:45:01 PM] Request textDocument/definition failed.
  Message: revenueperhour.proto:5:8: open buf/validate/validate.proto: no such file or directory
  Code: 0 
```

**Related Components**
- [ ] protoc-gen-grpc-federation
- [x] grpc-federation-linter
- [x] grpc-federation-language-server
- [ ] grpc-federation-generator
- [ ] others

**To Reproduce**
- Create a  `buf.yaml` like the following:
```yaml
version: v2
modules:
  - path: proto
deps:
  - buf.build/bufbuild/protovalidate
  - buf.build/googleapis/googleapis
 ```

- Create a `.proto` file with imports like the following:
```
import "google/protobuf/timestamp.proto";
```

**Expected behavior**
The import should be resolved by the vscode extension `mercari.grpc-federation` v1.0.2.

I am wondering if I am missing some configuration here or whether the extension should work with buf dependencies out of the box?

**Screenshots**
-

**Additional context**
-
